CREATE TABLE [dbo].[BookAuthor]
(
	[BookId] UNIQUEIDENTIFIER NOT NULL, 
    [AuthorId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_BOOKAUTHOR PRIMARY KEY(BookId, AuthorId),
	CONSTRAINT FK_BOOKAUTHOR_BOOK FOREIGN KEY (BookId) REFERENCES Book(Id),
	CONSTRAINT FK_BOOKAUTHOR_AUTHOR FOREIGN KEY (AuthorId) REFERENCES Author(Id)
)
